interface RepoData {
  archive_url: string;
  archived: string | boolean;
  assignees_url: string;
  blobs_url: string;
  branches_url: string;
  clone_url: string;
  collaborators_url: string;
  comments_url: string;
  commits_url: string;
  compare_url: string;
  contents_url: string;
  contributors_url: string;
  created_at: string;
  default_branch: string;
  deployments_url: string;
  description: string;
  disabled: string | boolean;
  downloads_url: string;
  events_url: string;
  fork: string | false;
  forks: string | number;
  forks_count: string | number;
  forks_url: string;
  full_name: string;
  git_commits_url: string;
  git_refs_url: string;
  git_tags_url: string;
  git_url: string;
  has_downloads: string | boolean;
  has_issues: string | boolean;
  has_pages: string | boolean;
  has_projects: string | boolean;
  has_wiki: string | boolean;
  homepage: string | null;
  hooks_url: string;
  html_url: string;
  id: string | number;
  issue_comment_url: string;
  issue_events_url: string;
  issues_url: string;
  keys_url: string;
  labels_url: string;
  language: string;
  languages_url: string;
  license: string | null;
  merges_url: string;
  milestones_url: string;
  mirror_url: string | null;
  name: string;
  network_count: string | number;
  node_id: string;
  notifications_url: string;
  open_issues: string | number;
  open_issues_count: string | number;
  owner: any;
  private: string | boolean;
  pulls_url: string;
  pushed_at: string;
  releases_url: string;
  size: string | number;
  ssh_url: string;
  stargazers_count: string | number;
  stargazers_url: string;
  statuses_url: string;
  subscribers_count: string | number;
  subscribers_url: string;
  subscription_url: string;
  svn_url: string;
  tags_url: string;
  teams_url: string;
  temp_clone_token: string | null;
  trees_url: string;
  updated_at: string;
  url: string;
  watchers: string | number;
  watchers_count: string | number;
}
export class Repo implements RepoData {
  archive_url!: string;
  archived!: string | boolean;
  assignees_url!: string;
  blobs_url!: string;
  branches_url!: string;
  clone_url!: string;
  collaborators_url!: string;
  comments_url!: string;
  commits_url!: string;
  compare_url!: string;
  contents_url!: string;
  contributors_url!: string;
  created_at!: string;
  default_branch!: string;
  deployments_url!: string;
  description!: string;
  disabled!: string | boolean;
  downloads_url!: string;
  events_url!: string;
  fork!: string | false;
  forks!: string | number;
  forks_count!: string | number;
  forks_url!: string;
  full_name!: string;
  git_commits_url!: string;
  git_refs_url!: string;
  git_tags_url!: string;
  git_url!: string;
  has_downloads!: string | boolean;
  has_issues!: string | boolean;
  has_pages!: string | boolean;
  has_projects!: string | boolean;
  has_wiki!: string | boolean;
  homepage!: string | null;
  hooks_url!: string;
  html_url!: string;
  id!: string | number;
  issue_comment_url!: string;
  issue_events_url!: string;
  issues_url!: string;
  keys_url!: string;
  labels_url!: string;
  language!: string;
  languages_url!: string;
  license!: string | null;
  merges_url!: string;
  milestones_url!: string;
  mirror_url!: string | null;
  name!: string;
  network_count!: string | number;
  node_id!: string;
  notifications_url!: string;
  open_issues!: string | number;
  open_issues_count!: string | number;
  owner: any;
  private!: string | boolean;
  pulls_url!: string;
  pushed_at!: string;
  releases_url!: string;
  size!: string | number;
  ssh_url!: string;
  stargazers_count!: string | number;
  stargazers_url!: string;
  statuses_url!: string;
  subscribers_count!: string | number;
  subscribers_url!: string;
  subscription_url!: string;
  svn_url!: string;
  tags_url!: string;
  teams_url!: string;
  temp_clone_token!: string | null;
  trees_url!: string;
  updated_at!: string;
  url!: string;
  watchers!: string | number;
  watchers_count!: string | number;

  constructor(data?: RepoData) {
    Object.assign(this, data);
  }
}
